//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_SOAP_SERVICE.ServiceReferenceSOAPPRODUCT {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://products.org/", ConfigurationName="ServiceReferenceSOAPPRODUCT.ProdSoapSoap")]
    public interface ProdSoapSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://products.org/Get_Details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Details();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://products.org/Get_Details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_DetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://products.org/Get_Product_name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Product_name(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://products.org/Get_Product_name", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Product_nameAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdSoapSoapChannel : DB_SOAP_SERVICE.ServiceReferenceSOAPPRODUCT.ProdSoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdSoapSoapClient : System.ServiceModel.ClientBase<DB_SOAP_SERVICE.ServiceReferenceSOAPPRODUCT.ProdSoapSoap>, DB_SOAP_SERVICE.ServiceReferenceSOAPPRODUCT.ProdSoapSoap {
        
        public ProdSoapSoapClient() {
        }
        
        public ProdSoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdSoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdSoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdSoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_Details() {
            return base.Channel.Get_Details();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_DetailsAsync() {
            return base.Channel.Get_DetailsAsync();
        }
        
        public System.Data.DataSet Get_Product_name(string s) {
            return base.Channel.Get_Product_name(s);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Product_nameAsync(string s) {
            return base.Channel.Get_Product_nameAsync(s);
        }
    }
}
